### ISSUE TITLE
Lost trailing spaces in commit messages

### ISSUE THREAD

**Issue by rousskov** [measurement-factory/bzr2git4notes#2]
I see many trailing spaces in comments removed during migration. For example, your Squid v5 r15057 commit has one. Trailing spaces are usually bugs/typos, but I do not know whether _all_ of them are, and the migration tool should not fix them.

This may be difficult or even impossible to fix (e.g., because git import or git log might insist on polishing commit messages), but if bzr2git4notes is responsible for this polishing, then please disable it.

**Comment by eduard-bagdasaryan** [comment]
>This may be difficult or even impossible to fix (e.g., because git import or git log might insist on polishing commit messages), but if bzr2git4notes is responsible for this polishing, then please disable it.

Looks like the tool does not change spaces in commit messages, but 'git fast-import' does. To check this, I compared results by importing a single r15057, having one space after 'workers.'. I have not found any related option for 'git fast-import', so it is probably not possible to control.

**Comment by rousskov** [comment]
Closing as "not worth fixing".

For the record, "git commit" eats trailing commit message spaces as well. I did check that the actual commit object in the git database does not have the trailing spaces.
