### ISSUE TITLE
Some committers are lost

### ISSUE THREAD

**Issue by rousskov** [measurement-factory/bzr2git4notes#3]
For example, Squid sourceformat r12284.2.1 (inside Squid trunk r12320 merge) has kinkie as the committer on the bzr side (with the author set to "p"), but the imported git commit does not mention kinkie at all! This particular example is weird and arguably unimportant, but there are probably other, potentially relevant ones (I just found this one first and stopped looking further).

**Comment by eduard-bagdasaryan** [comment]
> but the imported git commit does not mention kinkie at all

It does, please try  `git log --pretty=full --show-notes` command. Probably it is possible to configure that 'git log' showed both revision author and committer by default.

**Comment by rousskov** [comment]
Agreed. Closing as invalid. Sorry for the noise.
